# Generated by Django 5.0.6 on 2024-06-29 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('caption_heading', models.CharField(max_length=50)),
                ('caption_text', models.CharField(max_length=500)),
                ('is_published', models.BooleanField(default=False)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaHandeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('sequence_ind', models.PositiveSmallIntegerField(default=0)),
                ('media_file', models.FileField(upload_to='Posts/')),
                ('media_under_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_media', to='PostLikeComment.post')),
            ],
            options={
                'unique_together': {('sequence_ind', 'media_under_post')},
            },
        ),
    ]
