# Generated by Django 5.0.6 on 2024-06-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostLikeComment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediahandeling',
            old_name='sequence_ind',
            new_name='seq_no',
        ),
        migrations.AlterUniqueTogether(
            name='mediahandeling',
            unique_together={('seq_no', 'media_file')},
        ),
    ]
