# Generated by Django 5.0.6 on 2024-06-26 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_pic',
        ),
    ]
